# -*- coding: utf-8 -*-
"""PCA - without centering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ayEBaI0E9uOfAoMASwAPwoRAMy56DqDZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go

df=pd.read_csv('Dataset.csv', sep=',',header=None)

# X is a numpy array containing the 1000 datapoints
X = df.values
print(np.shape(X))

# Covariance matrix 
covariance_matrix = np.cov(X, rowvar= False)
print("Covariance Matrix = \n", covariance_matrix)

# Eigenvalues and Eigenvectors of the covariance matrix
eigen_values, eigen_vectors = np.linalg.eigh(covariance_matrix)
print("Eigenvalues : \n", eigen_values)
print("Eigenvectors : \n", eigen_vectors)